# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dev/messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dev/messages.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12\x64\x65v/messages.proto\"\xc4\x01\n\x14ProtoGyroDataStamped\x12\x15\n\rcapture_count\x18\x01 \x02(\x05\x12\x17\n\x0fraw_timer_count\x18\x02 \x02(\x03\x12\x11\n\tunix_secs\x18\x03 \x01(\x05\x12\x12\n\nunix_nsecs\x18\x04 \x01(\x05\x12\x15\n\rtim_unc_nsecs\x18\x05 \x01(\x05\x12\x0f\n\x07\x61\x64\x63_val\x18\x06 \x01(\x05\x12\t\n\x01x\x18\x07 \x02(\x02\x12\t\n\x01y\x18\x08 \x02(\x02\x12\t\n\x01z\x18\t \x02(\x02\x12\x0c\n\x04temp\x18\n \x01(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROTOGYRODATASTAMPED = _descriptor.Descriptor(
  name='ProtoGyroDataStamped',
  full_name='ProtoGyroDataStamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='capture_count', full_name='ProtoGyroDataStamped.capture_count', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='raw_timer_count', full_name='ProtoGyroDataStamped.raw_timer_count', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unix_secs', full_name='ProtoGyroDataStamped.unix_secs', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unix_nsecs', full_name='ProtoGyroDataStamped.unix_nsecs', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tim_unc_nsecs', full_name='ProtoGyroDataStamped.tim_unc_nsecs', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='adc_val', full_name='ProtoGyroDataStamped.adc_val', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='ProtoGyroDataStamped.x', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='ProtoGyroDataStamped.y', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='ProtoGyroDataStamped.z', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temp', full_name='ProtoGyroDataStamped.temp', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=219,
)

DESCRIPTOR.message_types_by_name['ProtoGyroDataStamped'] = _PROTOGYRODATASTAMPED

ProtoGyroDataStamped = _reflection.GeneratedProtocolMessageType('ProtoGyroDataStamped', (_message.Message,), dict(
  DESCRIPTOR = _PROTOGYRODATASTAMPED,
  __module__ = 'dev.messages_pb2'
  # @@protoc_insertion_point(class_scope:ProtoGyroDataStamped)
  ))
_sym_db.RegisterMessage(ProtoGyroDataStamped)


# @@protoc_insertion_point(module_scope)
