/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ProtoGyroDataStamped {
    int32_t capture_count;
    int64_t raw_timer_count;
    bool has_unix_secs;
    int32_t unix_secs;
    bool has_unix_nsecs;
    int32_t unix_nsecs;
    bool has_tim_unc_nsecs;
    int32_t tim_unc_nsecs;
    bool has_adc_val;
    int32_t adc_val;
    float x;
    float y;
    float z;
    bool has_temp;
    float temp;
/* @@protoc_insertion_point(struct:ProtoGyroDataStamped) */
} ProtoGyroDataStamped;


/* Initializer values for message structs */
#define ProtoGyroDataStamped_init_default        {0, 0, false, 0, false, 0, false, 0, false, 0, 0, 0, 0, false, 0}
#define ProtoGyroDataStamped_init_zero           {0, 0, false, 0, false, 0, false, 0, false, 0, 0, 0, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ProtoGyroDataStamped_capture_count_tag   1
#define ProtoGyroDataStamped_raw_timer_count_tag 2
#define ProtoGyroDataStamped_unix_secs_tag       3
#define ProtoGyroDataStamped_unix_nsecs_tag      4
#define ProtoGyroDataStamped_tim_unc_nsecs_tag   5
#define ProtoGyroDataStamped_adc_val_tag         6
#define ProtoGyroDataStamped_x_tag               7
#define ProtoGyroDataStamped_y_tag               8
#define ProtoGyroDataStamped_z_tag               9
#define ProtoGyroDataStamped_temp_tag            10

/* Struct field encoding specification for nanopb */
#define ProtoGyroDataStamped_FIELDLIST(X, a) \
X(a, STATIC, REQUIRED, INT32, capture_count, 1) \
X(a, STATIC, REQUIRED, INT64, raw_timer_count, 2) \
X(a, STATIC, OPTIONAL, INT32, unix_secs, 3) \
X(a, STATIC, OPTIONAL, INT32, unix_nsecs, 4) \
X(a, STATIC, OPTIONAL, INT32, tim_unc_nsecs, 5) \
X(a, STATIC, OPTIONAL, INT32, adc_val, 6) \
X(a, STATIC, REQUIRED, FLOAT, x, 7) \
X(a, STATIC, REQUIRED, FLOAT, y, 8) \
X(a, STATIC, REQUIRED, FLOAT, z, 9) \
X(a, STATIC, OPTIONAL, FLOAT, temp, 10)
#define ProtoGyroDataStamped_CALLBACK NULL
#define ProtoGyroDataStamped_DEFAULT NULL

extern const pb_msgdesc_t ProtoGyroDataStamped_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ProtoGyroDataStamped_fields &ProtoGyroDataStamped_msg

/* Maximum encoded size of messages (where known) */
#define ProtoGyroDataStamped_size                86

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
