/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ProtoIMUStamped {
    uint32_t capture_count;
    uint64_t raw_timer_count;
    bool has_unix_secs;
    uint32_t unix_secs;
    bool has_unix_nsecs;
    uint32_t unix_nsecs;
    bool has_tim_unc_nsecs;
    int32_t tim_unc_nsecs;
    bool has_adc_val;
    uint32_t adc_val;
    bool has_accx;
    float accx;
    bool has_accy;
    float accy;
    bool has_accz;
    float accz;
    bool has_rotx;
    float rotx;
    bool has_roty;
    float roty;
    bool has_rotz;
    float rotz;
    bool has_magx;
    float magx;
    bool has_magy;
    float magy;
    bool has_magz;
    float magz;
    bool has_temp;
    float temp;
    bool has_press;
    float press;
/* @@protoc_insertion_point(struct:ProtoIMUStamped) */
} ProtoIMUStamped;


/* Initializer values for message structs */
#define ProtoIMUStamped_init_default             {0, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ProtoIMUStamped_init_zero                {0, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ProtoIMUStamped_capture_count_tag        1
#define ProtoIMUStamped_raw_timer_count_tag      2
#define ProtoIMUStamped_unix_secs_tag            3
#define ProtoIMUStamped_unix_nsecs_tag           4
#define ProtoIMUStamped_tim_unc_nsecs_tag        5
#define ProtoIMUStamped_adc_val_tag              6
#define ProtoIMUStamped_accx_tag                 7
#define ProtoIMUStamped_accy_tag                 8
#define ProtoIMUStamped_accz_tag                 9
#define ProtoIMUStamped_rotx_tag                 13
#define ProtoIMUStamped_roty_tag                 14
#define ProtoIMUStamped_rotz_tag                 15
#define ProtoIMUStamped_magx_tag                 19
#define ProtoIMUStamped_magy_tag                 20
#define ProtoIMUStamped_magz_tag                 21
#define ProtoIMUStamped_temp_tag                 25
#define ProtoIMUStamped_press_tag                27

/* Struct field encoding specification for nanopb */
#define ProtoIMUStamped_FIELDLIST(X, a) \
X(a, STATIC, REQUIRED, UINT32, capture_count, 1) \
X(a, STATIC, REQUIRED, UINT64, raw_timer_count, 2) \
X(a, STATIC, OPTIONAL, UINT32, unix_secs, 3) \
X(a, STATIC, OPTIONAL, UINT32, unix_nsecs, 4) \
X(a, STATIC, OPTIONAL, INT32, tim_unc_nsecs, 5) \
X(a, STATIC, OPTIONAL, UINT32, adc_val, 6) \
X(a, STATIC, OPTIONAL, FLOAT, accx, 7) \
X(a, STATIC, OPTIONAL, FLOAT, accy, 8) \
X(a, STATIC, OPTIONAL, FLOAT, accz, 9) \
X(a, STATIC, OPTIONAL, FLOAT, rotx, 13) \
X(a, STATIC, OPTIONAL, FLOAT, roty, 14) \
X(a, STATIC, OPTIONAL, FLOAT, rotz, 15) \
X(a, STATIC, OPTIONAL, FLOAT, magx, 19) \
X(a, STATIC, OPTIONAL, FLOAT, magy, 20) \
X(a, STATIC, OPTIONAL, FLOAT, magz, 21) \
X(a, STATIC, OPTIONAL, FLOAT, temp, 25) \
X(a, STATIC, OPTIONAL, FLOAT, press, 27)
#define ProtoIMUStamped_CALLBACK NULL
#define ProtoIMUStamped_DEFAULT NULL

extern const pb_msgdesc_t ProtoIMUStamped_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ProtoIMUStamped_fields &ProtoIMUStamped_msg

/* Maximum encoded size of messages (where known) */
#define ProtoIMUStamped_size                     106

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
